sched: Add micro quanta scheduling class
Micro quanta is a lightweight scheduling class designed for
microsecond level scheduling intervals. It provides a more flexible
way to share cores between highly latency sensitive tasks with other
tasks - limiting the cpu share of latency sensitive tasks and
maintaining low scheduling latency at the same time.

The scheduling policy is similar to real-time group scheduling period
and runtime. There is no group support but more frequent context
switching is possible. Tasks running with 2us scheduling period and
1us runtime has been demonstrated. The practical range of microq
scheduling period is expected to be 10us ~ 1000us.

Kartikeya's note:

Original cover letter is available at [0]. This is a version rebased on
latest linux, and includes a log of conflicts and how they were
resolved.

Just reproducing the cover letter to make the patch description self
contained:

This is a scheduling class that does one thing really well:
microsecond level scheduling granularity. There are many problems
It doesn’t solve, e.g. there is minimal mutlicore support. Context
switch and cache overheads are going to be higher but we found
benefits outweigh drawbacks for certain applications.

It can be used in two different but related ways:

Provide softirq like scheduling latency for kernel and userspace
threads. Somewhat safer and easier to use than both softirq and rt
classes - microsecond level time slicing means a microq task can share
a cpu with a cfs task and still maintain low scheduling latency. With
rt classes users often have to choose between starving cfs tasks (rt
bandwidht control not activated) and high rt tail latency (rt
bandwidth control activated).

When busy polling is desired, we can run the busy polling thread under
the microq class with less than 100% of allocated cpu bandwidth. The
response latency would still be low and some cpu cycles are recovered
from the busy polling loop - it is a middle ground between interrupt
driven and busy polling.

  [0]: https://lore.kernel.org/all/20190906093412.233463-1-xii@google.com

Cc: Paul Turner <pjt@google.com>
Cc: Ben Segall <bsegall@google.com>'
Signed-off-by: Xi Wang <xii@google.com>
[ kkd: Rebase on bpf-next/master, reword commit message ]
Signed-off-by: Kumar Kartikeya Dwivedi <memxor@gmail.com>
--
When applying the patch on bpf-next/master (commit 1ffe30efd2f2e58c36b754c42c2b61906078a4cf),
we see:

	Applying: sched: Add micro quanta scheduling class
	Using index info to reconstruct a base tree...
	M       include/linux/sched.h
	M       include/linux/sched/sysctl.h
	M       include/uapi/linux/sched.h
	M       init/Kconfig
	M       kernel/sched/Makefile
	M       kernel/sched/core.c
	M       kernel/sched/debug.c
	M       kernel/sched/fair.c
	M       kernel/sched/pelt.c
	M       kernel/sched/pelt.h
	M       kernel/sched/rt.c
	M       kernel/sched/sched.h
	M       kernel/sysctl.c
	Falling back to patching base and 3-way merge...
	Auto-merging kernel/sysctl.c
	CONFLICT (content): Merge conflict in kernel/sysctl.c
	Auto-merging kernel/sched/sched.h
	CONFLICT (content): Merge conflict in kernel/sched/sched.h
	Auto-merging kernel/sched/rt.c
	CONFLICT (content): Merge conflict in kernel/sched/rt.c
	Auto-merging kernel/sched/pelt.h
	Auto-merging kernel/sched/pelt.c
	CONFLICT (content): Merge conflict in kernel/sched/pelt.c
	Auto-merging kernel/sched/fair.c
	CONFLICT (content): Merge conflict in kernel/sched/fair.c
	Auto-merging kernel/sched/debug.c
	Auto-merging kernel/sched/core.c
	CONFLICT (content): Merge conflict in kernel/sched/core.c
	Auto-merging kernel/sched/Makefile
	CONFLICT (content): Merge conflict in kernel/sched/Makefile
	Auto-merging init/Kconfig
	Auto-merging include/uapi/linux/sched.h
	CONFLICT (content): Merge conflict in include/uapi/linux/sched.h
	Auto-merging include/linux/sched/sysctl.h
	CONFLICT (content): Merge conflict in include/linux/sched/sysctl.h
	Auto-merging include/linux/sched.h
	CONFLICT (content): Merge conflict in include/linux/sched.h
	error: Failed to merge in the changes.
	Patch failed at 0001 sched: Add micro quanta scheduling class
	hint: Use 'git am --show-current-patch=diff' to see the failed patch
	When you have resolved this problem, run "git am --continue".
	If you prefer to skip this patch, run "git am --skip" instead.
	To restore the original branch and stop patching, run "git am --abort".

 * Fixed conflict in sysctl.c by moving sysctl to microq.c, made proc_handler
   static.
 * Fix minor conflict in kernel/sched/sched.h
 * Fix conflict in rt.c, rq->curr->sched_class diff moved to set_next_task_rt.
 * .next operation in sched_class is gone due to 590d69796346353878b275c5512c664e3f875f24
   in commit a87e749e8fa1aaef9b4db32e21c2795e69ce67bf
   We can move microq case there as well, but need to use DEFINE_SCHED_CLASS
   macro now.
   Resolve by adding it to include/asm-generic/vmlinux.lds.h
 * pelt.c conflict due to comment before __update_load_avg, resolve by moving hunk.
 * Conflict in kernel/sched/fair.c in __update_blocked_fair. Basically,
   whereever update_rt_rq_load_avg is called, we want to match on microq sched
   class as well. This got split into __update_blocked_others and
   sched_balance_update_blocked_averages. Do the change in
   __update_blocked_others.
 * kernel/sched/Makefile conflict because it moved to kernel/sched/build_policy.c
 * UAPI include/uapi/linux/sched.h renumber because of sched_ext
 * include/linux/sched/sysctl.h remove global sysctl + function declaration as
   it was moved to microq.c
 * include/linux/sched.h conflict with sched_ext to add per-task current->microq
 * kernel/sched/core.c: __setscheduler_params got moved to
   kernel/sched/syscalls.c, go there.
 * __setscheduler hunks readjusted based on f558c2b834ec27e75d37b1c860c139e7b7c3a8e4
   This then got shifted to __sched_setscheduler
 * rt_fiforr_policy change in user_check_sched_setscheduler for RLIMIT_RTPRIO
   since it got moved.
 * sched_getparam and get_param for sched_getattr
 * normal_prio change moved to __normal_prio
 * sched_class assignment moved to __setscheduler_class
 * EPERM for microq_policy moved to user_check_sched_setscheduler and changed to
   goto req_priv.

Now some changes to microq.c itself.
 * Rename task_running -> task_on_cpu due to
   0b9d46fc5ef7a457cc635b30b010081228cb81ac.
 * Make microq_task static function.
 * Comment pelt.h header include since build_policy.c already includes
   it, and it doesn't have guards, leading to double inclusion.
 * Add dummy declaration for microq_adjust_bandwidth to silence warning.
 * Need to use __schedstats_from_se instead of directly accessing
   curr->se.statistics in update_curr_microq.
 * Switch raw_spin_lock(rq->lock) to raw_spin_rq_lock(rq).
 * Switch h_nr_running to h_nr_queued in cfs_rq due to
   7b8a702d943827130cc00ae36075eff5500f86f1.
 * Switch callback_head to balance_callback due to
   8e5bad7dccec2014f24497b57d8a8ee0b752c290.
 * Fix ___update_load_avg(&rq->avg_rt, 1, 1); to just two params (2nd as 1).
 * Return true from dequeue_task_microq, as it now needs a bool return
   value, failure signalled using false since 863ccdbb918a77e3f011571f943020bf7f0b114b.
 * Do check_preempt_curr -> wakeup_preempt renaming due to
   e23edc86b09df655bf8963bbcb16647adc787395.
 * Remove pick_next_task_microq's rq_flags argument, e.g. see 98c2f700edb41. It
   was unused anyway.
 * put_prev_task_microq must take 3rd task_struct *next parameter, to
   match changes in commit b2d70222dbf2a2ff7a972a685d249a5d75afa87f for
   sched_ext, again the parameter is unused so no stress.
 * Convert away from sd_flag based on commit
   3aef1551e942860a3881087171ef0cd45f6ebda7 for select_task_rq_microq.
   SD_BALANCE_WAKE is WF_TTWU, SD_BALANCE_FORK is WF_FORK.
 * set_curr_task got renamed to set_next_task in 03b7fad167efc, perform.
 * The change to set_next_task is the most important one. Earlier, only
   rq parameter was passed to set_curr_task, and it would set the
   exec_start in the sched_entity of rq->curr. Now, we do it for task 'p',
   similar to rt and dl classes, and don't condition on first.
 * Lastly, note the change in set_next_task_rt for rt_rq->donor, which
   aliases rt_rq->curr.
 * Peter changed stats->exec_max to s64 in
   5d69eca542ee17c618f9a55da52191d5e28b435f, so cast to avoid error at
   compile time when using max (due to change in signedness).
 * Finally, proc_handler's first argument got const-ified, fix that for
   sched_microq_proc_handler callback.
--